### ISSUE TITLE
Consider removing _PID macros in device .h files

### ISSUE THREAD

**Issue by scottlaird** [linuxcnc-ethercat/linuxcnc-ethercat#154]
In general, dropping random numeric constants in code is bad form, but something about all of the per-device `LCEC_*_PID` definition in `.h` files feels off.  We use each of them exactly once (in `types[]`), and they're all right next to the device name anyway.

It's not clear to me how

```c
#define LCEC_EL3001_PID 0x0bb93052

static const lcec_typelist_t types[] = {
    {"EL3001", LCEC_BECKHOFF_VID, LCEC_EL3001_PID, LCEC_EL30X1_PDOS, 0, NULL, lcec_el3xxx_init, NULL, FLAG_BITS12},
    ...
}
```

is better than just inlining the PID like this:

```c
static const lcec_typelist_t types[] = {
    {"EL3001", LCEC_BECKHOFF_VID, 0x0bb93052, LCEC_EL30X1_PDOS, 0, NULL, lcec_el3xxx_init, NULL, FLAG_BITS12},
    ...
}
```

or maybe a trivial macro like this to make the type more obvious:

```c
static const lcec_typelist_t types[] = {
    {"EL3001", LCEC_BECKHOFF_VID, PID(0x0bb93052), LCEC_EL30X1_PDOS, 0, NULL, lcec_el3xxx_init, NULL, FLAG_BITS12},
    ...
}
```

**Comment by GuiHue** [comment]
Hi, love the effort of revitalising sittners work.
I consider your proposal to be the right way. I don't think the macro is all that important. 
I am not a software dev, but I have modified sittners drivers to include Delta ASDA-A3 (you guessed it: new PID). I wanted to create a PR from this. Which of the two options outlined above do you prefer for it?
