### ISSUE TITLE
lcec_el30x4.c: wrong value calculated

### ISSUE THREAD

**Issue by thomam04** [linuxcnc-ethercat/linuxcnc-ethercat#183]
Currently testing a few EL3xxx and noticed wrong value calculated in the EL30x4 vs EL31x2 driver. 

Typo in the 30x4.c driver:

    // update value
    value = EC_READ_S16(&pd[chan->val_pdo_os]);
    *(chan->raw_val) = value;
    *(chan->val) = *(chan->bias) + *(chan->scale) * (double)value * ((double)1/(double)0x7ff);

100% raw value should be based of 0x7fff (32,767) but it says 0x7ff (2047) in the driver.

**Comment by scottlaird** [comment]
FWIW, it should be v1.6.0

**Comment by scottlaird** [comment]
...and done.  https://build.opensuse.org/package/show/science:EtherLab/linuxcnc-ethercat

**Comment by thomam04** [comment]
Thanks. Problem resolved.
