### ISSUE TITLE
Beckhoff EL4031: ERROR 0 0:1: PDO entry 0x7000:11 is not mapped.

### ISSUE THREAD

**Issue by thomam04** [linuxcnc-ethercat/linuxcnc-ethercat#257]
With release 1.13.1 I am getting an: "ERROR 0 0:1: PDO entry 0x7000:11 is not mapped" with my EL4031. 

[Jan30 19:53] EtherCAT: Requesting master 0...
[  +0.000002] EtherCAT: Successfully requested master 0.
[  +0.384079] EtherCAT ERROR 0 0:1: PDO entry 0x7000:11 is not mapped.
[  +0.000026] EtherCAT 0: Releasing master...
[  +0.000035] EtherCAT 0: Released.

cnc@lcnc:~/ethercat$ ethercat slaves -p 1
1  0:1  PREOP  +  EL4031 1K. Ana. Ausgang +/-10V, 12bit
cnc@lcnc:~/ethercat$

**Comment by scottlaird** [comment]
Ah, okay, this might be a more interesting problem.  Which version of the EL4031 do you have?  Can you paste `ethercat slaves -v -p 1`?

I have an EL4032 r16, and it works fine as-is, but there's something weird about the EL40xxs, according to Beckhoff's documentation.  According to their ESI ZIP file, *most* of their EL4xxx devices use `0x7000:01` for output, but a few use `0x7000:11`.  Weirdly, the EL40xx family is documented as using `:11` on some software revisions and `:01` on others.  Beckhoff's [giant EL40xx PDF](https://download.beckhoff.com/download/Document/io/ethercat-terminals/EL40xxen.pdf) *doesn't* show this, and implies that they all use `:01`.

Ah.  Oops.

Nevermind, it's a bug.  *All* of the EL4xx1 devices are broken in 1.13.1.  Expect 1.13.2 in a couple minutes.

**Comment by thomam04** [comment]
Confirmed working again!
