### ISSUE TITLE
Typo in modParam value will result in "rtapi_app: caught signal 11 - dumping core"

### ISSUE THREAD

**Issue by thomam04** [linuxcnc-ethercat/linuxcnc-ethercat#259]
I noticed that a typo in the modParam value field results in a core dump (signal 11). 

It would be great to see / get an error message if the parameter is not found or not defined.

**Comment by scottlaird** [comment]
Which device?  Do you have a copy of the XML that lead to this?

The XML processing is mostly done per-device, so it's hard to track down the problem without more details.

**Comment by scottlaird** [comment]
Also -- did the core dump occur in `lcec_conf` or in `lcec`?

**Comment by thomam04** [comment]
This happened with the EL3204. I noticed it because I had added a custom sensor type in my driver/XML. You can replicate the issue with:
...
    <slave idx="13" type="EL3204" name="el3204-1">
        <modParam name="ch0Sensor" value="Pt1001"/>

Correct channel value would have been Pt1000. If you change it to Pt1001 it will crash. 

LinuxCNC Errors:
...
twopass: load_the_modules cmd=<orig_loadrt lcec>
waitpid failed /usr/bin/rtapi_app lcec
/usr/bin/rtapi_app exited without becoming ready
insmod for lcec failed, returned -1

Shutting down and cleaning up LinuxCNC...
Removing HAL_LIB, RTAPI, and Real Time OS modules
Removing NML shared memory segments

Debug file information:
Note: Using POSIX realtime
Unexpected realtime delay on task 0 with period 250000
This Message will only display once per session.
Run the Latency Test and resolve before continuing.
rtapi_app: caught signal 11 - dumping core

**Comment by scottlaird** [comment]
Hmm.  Okay, that really shouldn't be a problem.  And it's also something that I added recently.

*And* it's a bug that I'd ran into in a different way when rewriting the code, but haven't merged in yet.  #256 should fix this.  And I should add a test case for this.

**Comment by thomam04** [comment]
Tested and I can confirm it's working / gives an error message for unknown values. 

You rock Scott!
