### ISSUE TITLE
EL5101 frequency scale

### ISSUE THREAD

**Issue by hmnijp** [linuxcnc-ethercat/linuxcnc-ethercat#380]
While figuring out the EL5101 connection and trying to get the encoder frequency, I noticed that _HAL-pin.enc-frequency_ in the  [code](https://github.com/sittner/linuxcnc-ethercat/blob/87a8fd1f332cb96e5c073f8a12e806ffe30b06a3/src/lcec_el5101.c#L280C3-L280C98)  is:
 `*(hal_data->frequency) = ((double) (*(hal_data->raw_frequency))) * LCEC_EL5101_FREQUENCY_SCALE; ` 

The BeckHoff [manual](https://infosys.beckhoff.com/english.php?content=../content/1033/el5101/1862262283.html&id=4279442191079808877) says that
raw_frequency is an int number with a resolution of "0.01Hz"

but `#define LCEC_EL5101_FREQUENCY_SCALE = 5e-2` - I don’t understand why “5e-2”, but it gives the wrong enc-freq value

to obtain the pulse frequency in "Hz" it should have been "1e-2"? Or am I missing something and this has a different meaning?

this also affects EL5102. #167

**Comment by scottlaird** [comment]
That sounds like a bug, but I'm somewhat concerned that we probably have people depending on the wrong value, and have a 5x scale adjustment that they did themselves.

OTOH, frequency with encoders isn't *usually* the primary thing they're used for.

I'm travelling this week, but I'll look at this when I get home.

**Comment by scottlaird** [comment]
Adding `frequency-scale` is probably the best fix, *although* we might want to make it default to the old (wrong) value, just to keep it from breaking people's existing configs.  I'm still thinking about it.

If you want to send a PR for this, that'd be great.  If not, I can add it to my list.
