### ISSUE TITLE
About PDO mappings doc

### ISSUE THREAD

**Issue by jlama** [linuxcnc-ethercat/linuxcnc-ethercat#381]
Hi,

In pdos-and-syncs.md you wrote:

> The one possible issue here is performance--I suspect (but haven't verified) that our EtherCAT library will look for existing PDO sync mappings and pick the smallest one that covers the PDO objects that we care about, and then sync everything listed in that PDO.

I don't think this is correct.

First of all if `slave->sync_info` is set, any existing PDO assignments and mappings will be simply overwritten, so the above does not apply.

If PDOs mappings are not configured manually, only the default mappings (assigned to SM2 and SM3) will be considered. If you attempt to map a PDO entry not found in the default mappings, you'll get an error. But if the entry exists, then yes all entries listed in the mapping will be synced.

**Comment by scottlaird** [comment]
Ah, yeah, I should have been clearer that I meant "only if `sync_info` is unset".  I'll update the doc in a bit.

Is the SM2/SM3 case specific to Beckhoff, or is that a generic Ethercat thing?  I suppose I can dig through the Etherlab code to see how what they do...

Thanks for the review.  I'm still working my way through things here and keep finding things that are utterly undocumented and confusing, and I'm trying to document as I go and not be *too* wrong.

**Comment by jlama** [comment]
This is how the Etherlab master seems to do things. I just looked at the code. The relevant function is `ecrt_slave_config_reg_pdo_entry`.

**Comment by scottlaird** [comment]
Okay, I have some proposed changes in #382.  Care to take a look?

**Comment by jlama** [comment]
LGTM
