### ISSUE TITLE
Interact with the wider LinuxCNC community

### ISSUE THREAD

**Issue by scottlaird** [linuxcnc-ethercat/linuxcnc-ethercat#6]
Once we've caught up a bit, we should announce this to the wider LinuxCNC community.

**Comment by satiowadahc** [comment]
I mean we could interact with the wider community yet: https://github.com/sittner/linuxcnc-ethercat/issues/91

**Comment by scottlaird** [comment]
Posted https://forum.linuxcnc.org/ethercat/51187-new-linuxcnc-ethercat-git-tree

**Comment by scottlaird** [comment]
> I mean we could interact with the wider community yet: [sittner#91](https://github.com/sittner/linuxcnc-ethercat/issues/91)

I'd rather not rename things, but I'd be fine with reasonable patches that made things compatible with Machinekit.  I've never used it, so it's not really something that I'm motivated to do myself.
